//! Harness-native context packet pipeline.
//!
//! Consumes [`codex_repo_index::RepoMap`] and produces [`ContextPacket`] with a
//! mandatory [`ContextDecisionLog`]. Does not depend on how the map was built.

mod agent_eval;
mod assembler;
mod budgeter;
mod classifier;
mod decision_log;
mod eval;
mod metrics;
mod normalize;
pub mod ownership;
mod packet;
mod pipeline;
mod prompt_paths;
mod prompt_visibility;
mod render_level;
mod renderer;
mod run_memory;
mod selection;
mod task_scope;
mod task_terms;
mod test_select;

pub use agent_eval::AgentArm;
pub use agent_eval::AgentEvalComparison;
pub use agent_eval::AgentEvalReport;
pub use agent_eval::AgentEvalResult;
pub use agent_eval::AgentEvalTask;
pub use agent_eval::AgentEvalWorkdir;
pub use agent_eval::AgentRunInvalidReason;
pub use agent_eval::AgentRunRecord;
pub use agent_eval::AgentRunScore;
pub use agent_eval::AgentActivityCounts;
pub use agent_eval::ResultReason;
pub use agent_eval::TaskCategory;
pub use agent_eval::TokenUsageTotals;
pub use agent_eval::count_activity_from_exec_jsonl;
pub use agent_eval::intent_changed_files_from_exec_jsonl;
pub use agent_eval::agent_labels_from_task;
pub use agent_eval::build_report;
pub use agent_eval::changed_files_from_git_diff;
pub use agent_eval::classify_result;
pub use agent_eval::compare_task;
pub use agent_eval::count_turns_from_exec_jsonl;
pub use agent_eval::load_agent_eval_tasks;
pub use agent_eval::normalize_agent_eval_path;
pub use agent_eval::render_agent_eval_human;
pub use agent_eval::render_search_proxy_table;
pub use agent_eval::rollout_carries_harness_directive;
pub use agent_eval::score_run;
pub use agent_eval::search_proxy_proxy_state;
pub use agent_eval::search_proxy_report_row;
pub use agent_eval::SearchProxyReportRow;
pub use agent_eval::token_usage_from_exec_jsonl;
pub use assembler::ContextAssembler;
pub use budgeter::ContextBudgeter;
pub use budgeter::TokenBudget;
pub use classifier::TaskClassifier;
pub use classifier::TaskType;
pub use decision_log::ContextDecisionLog;
pub use decision_log::DecisionEntry;
pub use eval::EvalReport;
pub use eval::EvalTaskFixture;
pub use eval::load_eval_fixtures;
pub use eval::render_eval_human;
pub use eval::render_eval_summary;
pub use eval::run_eval;
pub use metrics::ContextMetrics;
pub use metrics::EvalDiagnostics;
pub use metrics::EvalLabels;
pub use metrics::Metrics;
pub use normalize::normalize_packet;
pub use packet::ContextItem;
pub use packet::ContextItemKind;
pub use packet::ContextItemState;
pub use packet::ContextPacket;
pub use packet::ContextStage;
pub use packet::RenderLevel;
pub use packet::SelectedTest;
pub use packet::TaskInfo;
pub use pipeline::BuildPacketOptions;
pub use pipeline::build_context_packet;
pub use prompt_paths::estimate_tokens_from_prompt_json;
pub use prompt_paths::extract_paths_from_prompt_json;
pub use prompt_visibility::model_prompt_contains_harness_context;
pub use prompt_visibility::user_message_texts;
pub use renderer::ContextPacketRenderer;
pub use renderer::EDIT_TARGETS_HEADER;
pub use renderer::ORIENTATION_HEADER;
pub use renderer::SCOPE_CONSTRAINT;
pub use run_memory::RunMemory;
pub use selection::SelectionCaps;
pub use task_scope::TaskScope;
pub use task_scope::infer_task_scope;
pub use task_terms::build_task_terms;
